/*
 * ModbusCommon.h
 *
 *  Created on: 2018¦~7¤ë9¤é
 *      Author: user
 */

#ifndef MODBUS_MODBUSCOMMON_H_
#define MODBUS_MODBUSCOMMON_H_

#include "driverlib.h"

enum {
    _CSTAT_NO_ACTION      =  (0x0000),
    _CSTAT_INIT_DRV_PARAM =  (0x0001<<0),
    _CSTAT_INIT_CLA_PARAM =  (0x0001<<1),
    _CSTAT_INIT_PWMADC    =  (0x0001<<2),
    _CSTAT_THREAD_READY   =  (_CSTAT_INIT_DRV_PARAM|_CSTAT_INIT_CLA_PARAM|_CSTAT_INIT_PWMADC),
    _CSTAT_INIT_PARAMS    =  (0x0001<<3),
    _CSTAT_INIT_SUCCESS   =  (_CSTAT_THREAD_READY|_CSTAT_INIT_PARAMS),
    _CSTAT_BROWN_IN       =  (0x0001<<6),
    _CSTAT_ENABLE_PWM     =  (0x0001<<7),
    _CSTAT_OUTPUT_READY   =  (_CSTAT_BROWN_IN|_CSTAT_ENABLE_PWM),
    _CSTAT_CALIBRATION    =  (0x0001<<8)
};

typedef int16_t FG_CLASTAT;

enum {
    _NO_ERROR     = (0x0000),
    _ERR_VO_OVP   = (0x0001<<0),
    _ERR_VIN_UVP  = (0x0001<<1),
    _ERR_IO_OCP   = (0x0001<<2),
    _ERR_VIN_OVP  = (0x0001<<3),
    _ALL_ERROR    = (_ERR_VO_OVP|_ERR_VIN_UVP|_ERR_IO_OCP|_ERR_VIN_OVP),
    _WARNING_VO   = (0x0001<<8),
    _WARNING_VIN  = (0x0001<<9),
    _WARNING_IO   = (0x0001<<10),
    _ALL_WARNING  = (_WARNING_VO|_WARNING_VIN|_WARNING_IO),
};

typedef uint16_t FG_CLAERR;

typedef volatile struct {

    FG_CLASTAT  fgStatus;
    FG_CLAERR   fgError;

    float32_t f32A;
    float32_t f32B;
    float32_t f32C;
    float32_t f32D;
    float32_t f32E;

    uint16_t SLAVE_ID;

}ST_DRV;

extern ST_DRV sDrv;

#define DEBUG_SCI_BASE SCIB_BASE
#define DEBUG_SCI_BAUDRATE 115200
#define DEBUG_SCI_CONFIG_WLEN SCI_CONFIG_WLEN_8
#define DEBUG_SCI_CONFIG_STOP SCI_CONFIG_STOP_ONE
#define DEBUG_SCI_CONFIG_PAR SCI_CONFIG_PAR_EVEN
#define DEBUG_SCI_FIFO_TX_LVL SCI_FIFO_TX0
#define DEBUG_SCI_FIFO_RX_LVL SCI_FIFO_RX0

//----

// Error codes
typedef enum {
	MB_NO_ERROR = 0,
	MB_ERROR_ILLEGALFUNC = 1,
	MB_ERROR_ILLEGALADDR,
	MB_ERROR_ILLEGALDATA,
	MB_ERROR_SLVFAILURE,
	MB_ERROR_ACKNOWLEDGE,
	MB_ERROR_SLVBUSY,
	MB_ERROR_NEGACKNOWLEDGE,
	MB_ERROR_MEMPARITY,
	MB_ERROR_GATEWAYPATHUN,
	MSG_ERROR_TIMEOUT = 9000
} MSG_ERROR_ID;

typedef enum {
	MB_READ_COIL_STATUS = 0x01,
	MB_READ_INPUT_STATUS = 0x02,
	MB_READ_HOLDING_REGISTERS = 0x03,
	MB_READ_INTPUT_REGISTERS = 0x04,
	MB_FORCE_SINGLE_COIL = 0x05,
	MB_PRESET_SINGLE_REGISTER = 0x06,
	MB_READ_EXCEPTION_STATUS = 0x07,
	MB_DIAGNOSTICS = 0x08,
	MB_PROGRAM_484 = 0x09,
	MB_POLL_484 = 0x0A,
	MB_FETCH_COMM_EVENT_CTR = 0x0B,
	MB_FETCH_COMM_EVENT_LOG = 0x0C,
	MB_PROGRAM_CONTROLLER = 0x0D,
	MB_POLL_CONTROLLER = 0x0E,
	MB_FORCE_MULTIPLE_COILS = 0x0F,
	MB_PRESET_MULTIPLE_REGISTERS = 0x10,
	MB_REPORT_SLAVE_ID = 0x11,
	MB_PROGRAM_884_M84 = 0x12,
	MB_RESET_COMM_LINK = 0x13,
	MB_READ_GENERAL_REFERENCE = 0x14,
	MB_WRITE_GENERAL_REFERENCE = 0x15,
	MB_MASK_WRITE_4X_REGISTER = 0x16,
	MB_READ_WRITE_4X_REGISTERS = 0x17,
	MB_READ_FIFO_QUEUE = 0x18,
	MB_END_OF_FUNCID,
	MB_ERROR_MASK = 0X80
} MB_FUNC_ID;

#define END_OF_FUNCTION			(MB_END_OF_FUNCID-1)

#define BROADCAST_ID            0

#define mbT35 (unsigned long) 5000  //1750
#define mbT15 (unsigned long) 750

#define MB_Q15toSF(q15)  (float32_t)((float32_t)q15/32768.0f)
#define MB_SFtoQ15(sf)   (int16_t)(sf*32768.0f)

#endif /* MODBUS_MODBUSCOMMON_H_ */
